<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CD Case Front Cover Generator</title>
<style>
  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
  }
  .container {
    width: 111mm; /* PlayStation 1 game case width */
    height: 111mm; /* PlayStation 1 game case height */
    background-color: #fff;
    border: 1px solid #000;
    position: relative;
    margin: 50px auto;
    box-sizing: border-box;
    background-image: url('https://github.com/xlenore/psx-covers/blob/main/covers/custom/SCES-00967.jpg?raw=true');
    background-size:cover;
  }
  .sticker {
    width: 72px;
    height: 72px;
    background-color: #ffff00;
    position: absolute;
  }
  .sticker2 {
    width: 72px;
    height: 10px;
    background-color: #ffffff;
    border:1px solid #000;
    position: absolute;
    top: 100px !important;
    left: 10px !important;
    text-align:center;
    font-size:0.585rem;
    font-weight:bold;
    overflow-y:hidden;
    overflow-x:hidden;
  }
  .sticker.left {
    left: 10px;
  }
  .sticker.top {
    top: 10px;
  }
  .sticker.bottom {
    bottom: 7px;
  }
  .black-line {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 86px; /* Height of the black line */
    background-color: #000;
    color: #fff;
    text-align: center;
    line-height: 15px; /* Vertical alignment */
  }
  .playstation-logo {
    display: inline-block;
    width: 15px; /* Width of the PlayStation logo */
    height: 15px;
    background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/PlayStation_logo.svg/1200px-PlayStation_logo.svg.png');
    background-size: contain;
    background-repeat: no-repeat;
  }
  #ps-logo{
  	position:absolute;
    top:2em;
    right:9.5em;
  }
</style>
</head>
<body>

<div class="container" id="cdCover">
  <div class="black-line">
    <span class="playstation-logo"></span> <span id="ps-logo"><strong><b>PlayStation</b></strong></span>
  </div>
</div>

<script>
function generate_cover() {
  // Call this function to generate the CD cover
  
  // Create the container for CD cover
  var container = document.getElementById('cdCover');
  
  // Create the stickers
  var stickerTopLeft = document.createElement('div');
  stickerTopLeft.className = 'sticker left top';
  container.appendChild(stickerTopLeft);

  // Create the stickers
  var stickerTopLeft2 = document.createElement('div');
  stickerTopLeft2.className = 'sticker2 left top';
  container.appendChild(stickerTopLeft2);
  
  var stickerBottomLeft = document.createElement('div');
  stickerBottomLeft.className = 'sticker left bottom';
  container.appendChild(stickerBottomLeft);

  // Set the innerHTML of the container to the image HTML
  var elements = document.getElementsByClassName("sticker2");
	for (var i = 0; i < elements.length; i++) {
    	elements[i].innerHTML = 'PAL';
	}
}
// Call the generate_cover function when the page loads
generate_cover();
</script>

</body>
</html>
